
export const mockedData = { "results": [
  {
       "congress": "116",
       "chamber": "Senate",
       "num_results": 100,
       "offset": 0,
       "members": [
            {
               "id": "A000360",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/A000360.json",
               "first_name": "Lamar",
               "middle_name": null,
               "last_name": "Alexander",
               "suffix": null,
               "date_of_birth": "1940-07-03",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenAlexander",
               "facebook_account": "senatorlamaralexander",
               "youtube_account": "lamaralexander",
               "govtrack_id": "300002",
               "cspan_id": "5",
               "votesmart_id": "15691",
               "icpsr_id": "40304",
               "crp_id": "N00009888",
               "google_entity_id": "/m/01rbs3",
               "fec_candidate_id": "S2TN00058",
               "url": "https://www.alexander.senate.gov/public",
               "rss_url": "https://www.alexander.senate.gov/public/?a=RSS.Feed",
               "contact_form": "http://www.alexander.senate.gov/public/index.cfm?p=Email",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.324,
               "ideal_point": null,
               "seniority": "17",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 76,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:tn",
               "office": "455 Dirksen Senate Office Building",
               "phone": "202-224-4944",
               "fax": "202-228-3398",
               "state": "TN",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S289"
               ,"missed_votes_pct": 19.19,
               "votes_with_party_pct": 97.18,
               "votes_against_party_pct": 2.82
             },
                         {
               "id": "B001230",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001230.json",
               "first_name": "Tammy",
               "middle_name": null,
               "last_name": "Baldwin",
               "suffix": null,
               "date_of_birth": "1962-02-11",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenatorBaldwin",
               "facebook_account": "senatortammybaldwin",
               "youtube_account": "witammybaldwin",
               "govtrack_id": "400013",
               "cspan_id": "57884",
               "votesmart_id": "3470",
               "icpsr_id": "29940",
               "crp_id": "N00004367",
               "google_entity_id": "/m/024v02",
               "fec_candidate_id": "H8WI00018",
               "url": "https://www.baldwin.senate.gov",
               "rss_url": "https://www.baldwin.senate.gov/rss/feeds/?type=all",
               "contact_form": "https://www.baldwin.senate.gov/feedback",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.502,
               "ideal_point": null,
               "seniority": "7",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 1,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:wi",
               "office": "709 Hart Senate Office Building",
               "phone": "202-224-5653",
               "fax": null,
               "state": "WI",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S354"
               ,"missed_votes_pct": 0.25,
               "votes_with_party_pct": 93.98,
               "votes_against_party_pct": 6.02
             },
                         {
               "id": "B001261",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001261.json",
               "first_name": "John",
               "middle_name": null,
               "last_name": "Barrasso",
               "suffix": null,
               "date_of_birth": "1952-07-21",
               "gender": "M",
               "party": "R",
               "leadership_role": "Senate Republican Conference Chair",
               "twitter_account": "SenJohnBarrasso",
               "facebook_account": "johnbarrasso",
               "youtube_account": "barrassowyo",
               "govtrack_id": "412251",
               "cspan_id": "1024777",
               "votesmart_id": "52662",
               "icpsr_id": "40707",
               "crp_id": "N00006236",
               "google_entity_id": "/m/02rsm32",
               "fec_candidate_id": "S6WY00068",
               "url": "https://www.barrasso.senate.gov",
               "rss_url": "https://www.barrasso.senate.gov/public/?a=rss.feed",
               "contact_form": "https://www.barrasso.senate.gov/public/index.cfm/contact-form",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.538,
               "ideal_point": null,
               "seniority": "13",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:33 -0500",
               "ocd_id": "ocd-division/country:us/state:wy",
               "office": "307 Dirksen Senate Office Building",
               "phone": "202-224-6441",
               "fax": null,
               "state": "WY",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S317"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 96.95,
               "votes_against_party_pct": 3.05
             },
                         {
               "id": "B001267",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001267.json",
               "first_name": "Michael",
               "middle_name": null,
               "last_name": "Bennet",
               "suffix": null,
               "date_of_birth": "1964-11-28",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenBennetCo",
               "facebook_account": "senbennetco",
               "youtube_account": "SenatorBennet",
               "govtrack_id": "412330",
               "cspan_id": "1031622",
               "votesmart_id": "110942",
               "icpsr_id": "40910",
               "crp_id": "N00030608",
               "google_entity_id": "/m/05b60qf",
               "fec_candidate_id": "S0CO00211",
               "url": "https://www.bennet.senate.gov/public",
               "rss_url": null,
               "contact_form": "https://www.bennet.senate.gov/public/index.cfm/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.218,
               "ideal_point": null,
               "seniority": "11",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 116,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:co",
               "office": "261 Russell Senate Office Building",
               "phone": "202-224-5852",
               "fax": "202-228-5097",
               "state": "CO",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S330"
               ,"missed_votes_pct": 29.29,
               "votes_with_party_pct": 93.38,
               "votes_against_party_pct": 6.62
             },
                         {
               "id": "B001243",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001243.json",
               "first_name": "Marsha",
               "middle_name": null,
               "last_name": "Blackburn",
               "suffix": null,
               "date_of_birth": "1952-06-06",
               "gender": "F",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "MarshaBlackburn",
               "facebook_account": "marshablackburn",
               "youtube_account": "RepMarshaBlackburn",
               "govtrack_id": "400032",
               "cspan_id": "31226",
               "votesmart_id": "25186",
               "icpsr_id": "20351",
               "crp_id": "N00003105",
               "google_entity_id": "/m/01fnkt",
               "fec_candidate_id": "H2TN06030",
               "url": "https://www.blackburn.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.blackburn.senate.gov/contact_marsha",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.617,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 3,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:tn",
               "office": "357 Dirksen Senate Office Building",
               "phone": "202-224-3344",
               "fax": null,
               "state": "TN",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S396"
               ,"missed_votes_pct": 0.76,
               "votes_with_party_pct": 93.09,
               "votes_against_party_pct": 6.91
             },
                         {
               "id": "B001277",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001277.json",
               "first_name": "Richard",
               "middle_name": null,
               "last_name": "Blumenthal",
               "suffix": null,
               "date_of_birth": "1946-02-13",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenBlumenthal",
               "facebook_account": "SenBlumenthal",
               "youtube_account": "SenatorBlumenthal",
               "govtrack_id": "412490",
               "cspan_id": "21799",
               "votesmart_id": "1568",
               "icpsr_id": "41101",
               "crp_id": "N00031685",
               "google_entity_id": "/m/03tg8m",
               "fec_candidate_id": "S0CT00177",
               "url": "https://www.blumenthal.senate.gov",
               "rss_url": "https://www.blumenthal.senate.gov/rss/feeds/?type=press",
               "contact_form": "https://www.blumenthal.senate.gov/contact/",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.432,
               "ideal_point": null,
               "seniority": "9",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 4,
               "total_present": 1,
               "last_updated": "2019-12-13 16:25:22 -0500",
               "ocd_id": "ocd-division/country:us/state:ct",
               "office": "706 Hart Senate Office Building",
               "phone": "202-224-2823",
               "fax": "202-224-9673",
               "state": "CT",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S341"
               ,"missed_votes_pct": 1.01,
               "votes_with_party_pct": 89.71,
               "votes_against_party_pct": 10.29
             },
                         {
               "id": "B000575",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B000575.json",
               "first_name": "Roy",
               "middle_name": null,
               "last_name": "Blunt",
               "suffix": null,
               "date_of_birth": "1950-01-10",
               "gender": "M",
               "party": "R",
               "leadership_role": "Senate Republican Policy Committee Chair",
               "twitter_account": "RoyBlunt",
               "facebook_account": "SenatorBlunt",
               "youtube_account": "SenatorBlunt",
               "govtrack_id": "400034",
               "cspan_id": "45465",
               "votesmart_id": "418",
               "icpsr_id": "29735",
               "crp_id": "N00005195",
               "google_entity_id": "/m/034fn4",
               "fec_candidate_id": "S0MO00183",
               "url": "https://www.blunt.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.blunt.senate.gov/public/index.cfm/contact-roy",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.428,
               "ideal_point": null,
               "seniority": "9",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 4,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:mo",
               "office": "260 Russell Senate Office Building",
               "phone": "202-224-5721",
               "fax": "202-224-8149",
               "state": "MO",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S342"
               ,"missed_votes_pct": 1.01,
               "votes_with_party_pct": 98.46,
               "votes_against_party_pct": 1.54
             },
                         {
               "id": "B001288",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001288.json",
               "first_name": "Cory",
               "middle_name": null,
               "last_name": "Booker",
               "suffix": null,
               "date_of_birth": "1969-04-27",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenBooker",
               "facebook_account": null,
               "youtube_account": "SenCoryBooker",
               "govtrack_id": "412598",
               "cspan_id": "84679",
               "votesmart_id": "76151",
               "icpsr_id": "41308",
               "crp_id": "N00035267",
               "google_entity_id": "/m/06p430",
               "fec_candidate_id": "S4NJ00185",
               "url": "https://www.booker.senate.gov",
               "rss_url": "https://www.booker.senate.gov/rss/",
               "contact_form": "https://www.booker.senate.gov/?p=contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.609,
               "ideal_point": null,
               "seniority": "7",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 245,
               "total_present": 1,
               "last_updated": "2019-12-13 16:25:22 -0500",
               "ocd_id": "ocd-division/country:us/state:nj",
               "office": "717 Hart Senate Office Building",
               "phone": "202-224-3224",
               "fax": "202-224-8378",
               "state": "NJ",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S370"
               ,"missed_votes_pct": 61.87,
               "votes_with_party_pct": 80.54,
               "votes_against_party_pct": 19.46
             },
                         {
               "id": "B001236",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001236.json",
               "first_name": "John",
               "middle_name": null,
               "last_name": "Boozman",
               "suffix": null,
               "date_of_birth": "1950-12-10",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "JohnBoozman",
               "facebook_account": "JohnBoozman",
               "youtube_account": "BoozmanPressOffice",
               "govtrack_id": "400040",
               "cspan_id": "92069",
               "votesmart_id": "27958",
               "icpsr_id": "20101",
               "crp_id": "N00013873",
               "google_entity_id": "/m/024s3v",
               "fec_candidate_id": "H2AR03176",
               "url": "https://www.boozman.senate.gov/public",
               "rss_url": "https://www.boozman.senate.gov/public/?a=RSS.Feed",
               "contact_form": "https://www.boozman.senate.gov/public/index.cfm/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.4,
               "ideal_point": null,
               "seniority": "9",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:ar",
               "office": "141 Hart Senate Office Building",
               "phone": "202-224-4843",
               "fax": "202-228-1371",
               "state": "AR",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S343"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 98.22,
               "votes_against_party_pct": 1.78
             },
                         {
               "id": "B001310",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001310.json",
               "first_name": "Mike",
               "middle_name": null,
               "last_name": "Braun",
               "suffix": null,
               "date_of_birth": "1954-03-24",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenatorBraun",
               "facebook_account": null,
               "youtube_account": null,
               "govtrack_id": "412839",
               "cspan_id": null,
               "votesmart_id": "148564",
               "icpsr_id": null,
               "crp_id": "N00041731",
               "google_entity_id": "/g/11f2ckdwty",
               "fec_candidate_id": "S8IN00171",
               "url": "https://www.braun.senate.gov",
               "rss_url": null,
               "contact_form": "http://www.braun.senate.gov/contact-mike",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": null,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 2,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:in",
               "office": "374 Russell Senate Office Building",
               "phone": "202-224-4814",
               "fax": null,
               "state": "IN",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S397"
               ,"missed_votes_pct": 0.51,
               "votes_with_party_pct": 94.13,
               "votes_against_party_pct": 5.87
             },
                         {
               "id": "B000944",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B000944.json",
               "first_name": "Sherrod",
               "middle_name": null,
               "last_name": "Brown",
               "suffix": null,
               "date_of_birth": "1952-11-09",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenSherrodBrown",
               "facebook_account": "SenatorSherrodBrown",
               "youtube_account": "SherrodBrownOhio",
               "govtrack_id": "400050",
               "cspan_id": "5051",
               "votesmart_id": "27018",
               "icpsr_id": "29389",
               "crp_id": "N00003535",
               "google_entity_id": "/m/034s80",
               "fec_candidate_id": "H2OH13033",
               "url": "https://www.brown.senate.gov",
               "rss_url": "https://www.brown.senate.gov/rss/feeds/?type=all&",
               "contact_form": "http://www.brown.senate.gov/contact/",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.433,
               "ideal_point": null,
               "seniority": "13",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 3,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:43 -0500",
               "ocd_id": "ocd-division/country:us/state:oh",
               "office": "503 Hart Senate Office Building",
               "phone": "202-224-2315",
               "fax": null,
               "state": "OH",
               "senate_class": "1",
               "state_rank": "senior",
               "lis_id": "S307"
               ,"missed_votes_pct": 0.76,
               "votes_with_party_pct": 91.58,
               "votes_against_party_pct": 8.42
             },
                         {
               "id": "B001135",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/B001135.json",
               "first_name": "Richard",
               "middle_name": "M.",
               "last_name": "Burr",
               "suffix": null,
               "date_of_birth": "1955-11-30",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenatorBurr",
               "facebook_account": "SenatorRichardBurr",
               "youtube_account": "SenatorRichardBurr",
               "govtrack_id": "400054",
               "cspan_id": "31054",
               "votesmart_id": "21787",
               "icpsr_id": "29548",
               "crp_id": "N00002221",
               "google_entity_id": "/m/03g_s9",
               "fec_candidate_id": "S4NC00089",
               "url": "https://www.burr.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.burr.senate.gov/contact/email",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.451,
               "ideal_point": null,
               "seniority": "15",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 37,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:43 -0500",
               "ocd_id": "ocd-division/country:us/state:nc",
               "office": "217 Russell Senate Office Building",
               "phone": "202-224-3154",
               "fax": "202-228-2981",
               "state": "NC",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S300"
               ,"missed_votes_pct": 9.34,
               "votes_with_party_pct": 98.88,
               "votes_against_party_pct": 1.12
             },
                         {
               "id": "C000127",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C000127.json",
               "first_name": "Maria",
               "middle_name": null,
               "last_name": "Cantwell",
               "suffix": null,
               "date_of_birth": "1958-10-13",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenatorCantwell",
               "facebook_account": "senatorcantwell",
               "youtube_account": "SenatorCantwell",
               "govtrack_id": "300018",
               "cspan_id": "26137",
               "votesmart_id": "27122",
               "icpsr_id": "39310",
               "crp_id": "N00007836",
               "google_entity_id": "/m/01x68t",
               "fec_candidate_id": "S8WA00194",
               "url": "https://www.cantwell.senate.gov",
               "rss_url": null,
               "contact_form": "http://www.cantwell.senate.gov/public/index.cfm/email-maria",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.298,
               "ideal_point": null,
               "seniority": "19",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 2,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:wa",
               "office": "511 Hart Senate Office Building",
               "phone": "202-224-3441",
               "fax": null,
               "state": "WA",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S275"
               ,"missed_votes_pct": 0.51,
               "votes_with_party_pct": 92.15,
               "votes_against_party_pct": 7.85
             },
                         {
               "id": "C001047",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001047.json",
               "first_name": "Shelley",
               "middle_name": "Moore",
               "last_name": "Capito",
               "suffix": null,
               "date_of_birth": "1953-11-26",
               "gender": "F",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenCapito",
               "facebook_account": "senshelley",
               "youtube_account": null,
               "govtrack_id": "400061",
               "cspan_id": "83737",
               "votesmart_id": "11701",
               "icpsr_id": "20146",
               "crp_id": "N00009771",
               "google_entity_id": "/m/024pwq",
               "fec_candidate_id": "H0WV02138",
               "url": "https://www.capito.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.capito.senate.gov/contact/contact-shelley",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.262,
               "ideal_point": null,
               "seniority": "5",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 11,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:wv",
               "office": "172 Russell Senate Office Building",
               "phone": "202-224-6472",
               "fax": "202-225-7856",
               "state": "WV",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S372"
               ,"missed_votes_pct": 2.78,
               "votes_with_party_pct": 98.44,
               "votes_against_party_pct": 1.56
             },
                         {
               "id": "C000141",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C000141.json",
               "first_name": "Benjamin",
               "middle_name": "L.",
               "last_name": "Cardin",
               "suffix": null,
               "date_of_birth": "1943-10-05",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenatorCardin",
               "facebook_account": "senatorbencardin",
               "youtube_account": "senatorcardin",
               "govtrack_id": "400064",
               "cspan_id": "4004",
               "votesmart_id": "26888",
               "icpsr_id": "15408",
               "crp_id": "N00001955",
               "google_entity_id": "/m/025k3k",
               "fec_candidate_id": "H6MD03177",
               "url": "https://www.cardin.senate.gov",
               "rss_url": null,
               "contact_form": "http://www.cardin.senate.gov/contact/",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.322,
               "ideal_point": null,
               "seniority": "13",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 3,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:md",
               "office": "509 Hart Senate Office Building",
               "phone": "202-224-4524",
               "fax": null,
               "state": "MD",
               "senate_class": "1",
               "state_rank": "senior",
               "lis_id": "S308"
               ,"missed_votes_pct": 0.76,
               "votes_with_party_pct": 94.21,
               "votes_against_party_pct": 5.79
             },
                         {
               "id": "C000174",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C000174.json",
               "first_name": "Thomas",
               "middle_name": "R.",
               "last_name": "Carper",
               "suffix": null,
               "date_of_birth": "1947-01-23",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenatorCarper",
               "facebook_account": "tomcarper",
               "youtube_account": "senatorcarper",
               "govtrack_id": "300019",
               "cspan_id": "663",
               "votesmart_id": "22421",
               "icpsr_id": "15015",
               "crp_id": "N00012508",
               "google_entity_id": "/m/01xw7t",
               "fec_candidate_id": "S8DE00079",
               "url": "https://www.carper.senate.gov/public",
               "rss_url": "https://www.carper.senate.gov/public/?a=RSS.Feed",
               "contact_form": "http://www.carper.senate.gov/public/index.cfm/email-senator-carper",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.176,
               "ideal_point": null,
               "seniority": "19",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 3,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:de",
               "office": "513 Hart Senate Office Building",
               "phone": "202-224-2441",
               "fax": null,
               "state": "DE",
               "senate_class": "1",
               "state_rank": "senior",
               "lis_id": "S277"
               ,"missed_votes_pct": 0.76,
               "votes_with_party_pct": 89.47,
               "votes_against_party_pct": 10.53
             },
                         {
               "id": "C001070",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001070.json",
               "first_name": "Bob",
               "middle_name": null,
               "last_name": "Casey",
               "suffix": null,
               "date_of_birth": "1960-04-13",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenBobCasey",
               "facebook_account": "SenatorBobCasey",
               "youtube_account": "SenatorBobCasey",
               "govtrack_id": "412246",
               "cspan_id": "47036",
               "votesmart_id": "2541",
               "icpsr_id": "40703",
               "crp_id": "N00027503",
               "google_entity_id": "/m/047ymw",
               "fec_candidate_id": "S6PA00217",
               "url": "https://www.casey.senate.gov",
               "rss_url": "https://www.casey.senate.gov/rss/feeds/?all",
               "contact_form": "https://www.casey.senate.gov/contact/",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.306,
               "ideal_point": null,
               "seniority": "13",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:pa",
               "office": "393 Russell Senate Office Building",
               "phone": "202-224-6324",
               "fax": null,
               "state": "PA",
               "senate_class": "1",
               "state_rank": "senior",
               "lis_id": "S309"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 94.52,
               "votes_against_party_pct": 5.48
             },
                         {
               "id": "C001075",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001075.json",
               "first_name": "Bill",
               "middle_name": null,
               "last_name": "Cassidy",
               "suffix": null,
               "date_of_birth": "1957-09-28",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": null,
               "facebook_account": null,
               "youtube_account": "SenatorBillCassidy",
               "govtrack_id": "412269",
               "cspan_id": "1030546",
               "votesmart_id": "69494",
               "icpsr_id": "20919",
               "crp_id": "N00030245",
               "google_entity_id": "/m/0286t7r",
               "fec_candidate_id": "H8LA00017",
               "url": "https://www.cassidy.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.cassidy.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.452,
               "ideal_point": null,
               "seniority": "5",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 38,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:la",
               "office": "520 Hart Senate Office Building",
               "phone": "202-224-5824",
               "fax": "202-225-7313",
               "state": "LA",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S373"
               ,"missed_votes_pct": 9.60,
               "votes_with_party_pct": 99.44,
               "votes_against_party_pct": 0.56
             },
                         {
               "id": "C001035",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001035.json",
               "first_name": "Susan",
               "middle_name": null,
               "last_name": "Collins",
               "suffix": null,
               "date_of_birth": "1952-12-07",
               "gender": "F",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenatorCollins",
               "facebook_account": "susancollins",
               "youtube_account": "SenatorSusanCollins",
               "govtrack_id": "300025",
               "cspan_id": "45738",
               "votesmart_id": "379",
               "icpsr_id": "49703",
               "crp_id": "N00000491",
               "google_entity_id": "/m/020y8m",
               "fec_candidate_id": "S6ME00159",
               "url": "https://www.collins.senate.gov",
               "rss_url": "https://www.collins.senate.gov/?q=rss.xml",
               "contact_form": "http://www.collins.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.112,
               "ideal_point": null,
               "seniority": "23",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:me",
               "office": "413 Dirksen Senate Office Building",
               "phone": "202-224-2523",
               "fax": "202-224-2693",
               "state": "ME",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S252"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 87.82,
               "votes_against_party_pct": 12.18
             },
                         {
               "id": "C001088",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001088.json",
               "first_name": "Christopher",
               "middle_name": "A.",
               "last_name": "Coons",
               "suffix": null,
               "date_of_birth": "1963-09-09",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "ChrisCoons",
               "facebook_account": "senatorchriscoons",
               "youtube_account": "senatorchriscoons",
               "govtrack_id": "412390",
               "cspan_id": "9269028",
               "votesmart_id": "122834",
               "icpsr_id": "40916",
               "crp_id": "N00031820",
               "google_entity_id": "/m/082d3d",
               "fec_candidate_id": "S0DE00092",
               "url": "https://www.coons.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.coons.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.224,
               "ideal_point": null,
               "seniority": "11",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 16,
               "total_present": 1,
               "last_updated": "2019-12-13 16:25:22 -0500",
               "ocd_id": "ocd-division/country:us/state:de",
               "office": "218 Russell Senate Office Building",
               "phone": "202-224-5042",
               "fax": "202-228-3075",
               "state": "DE",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S337"
               ,"missed_votes_pct": 4.04,
               "votes_with_party_pct": 91.30,
               "votes_against_party_pct": 8.70
             },
                         {
               "id": "C001056",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001056.json",
               "first_name": "John",
               "middle_name": null,
               "last_name": "Cornyn",
               "suffix": null,
               "date_of_birth": "1952-02-02",
               "gender": "M",
               "party": "R",
               "leadership_role": "Senate Majority Whip",
               "twitter_account": "JohnCornyn",
               "facebook_account": "sen.johncornyn",
               "youtube_account": "senjohncornyn",
               "govtrack_id": "300027",
               "cspan_id": "93131",
               "votesmart_id": "15375",
               "icpsr_id": "40305",
               "crp_id": "N00024852",
               "google_entity_id": "/m/01xcqs",
               "fec_candidate_id": "S2TX00106",
               "url": "https://www.cornyn.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.cornyn.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.495,
               "ideal_point": null,
               "seniority": "17",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 4,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:tx",
               "office": "517 Hart Senate Office Building",
               "phone": "202-224-2934",
               "fax": "202-228-2856",
               "state": "TX",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S287"
               ,"missed_votes_pct": 1.01,
               "votes_with_party_pct": 98.97,
               "votes_against_party_pct": 1.03
             },
                         {
               "id": "C001113",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001113.json",
               "first_name": "Catherine",
               "middle_name": null,
               "last_name": "Cortez Masto",
               "suffix": null,
               "date_of_birth": "1964-03-29",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "sencortezmasto",
               "facebook_account": "SenatorCortezMasto",
               "youtube_account": null,
               "govtrack_id": "412681",
               "cspan_id": "105698",
               "votesmart_id": "69579",
               "icpsr_id": "41700",
               "crp_id": "N00037161",
               "google_entity_id": "/m/02rtp9t",
               "fec_candidate_id": "S6NV00200",
               "url": "https://www.cortezmasto.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.cortezmasto.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.377,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 3,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:nv",
               "office": "516 Hart Senate Office Building",
               "phone": "202-224-3542",
               "fax": null,
               "state": "NV",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S385"
               ,"missed_votes_pct": 0.76,
               "votes_with_party_pct": 95.53,
               "votes_against_party_pct": 4.47
             },
                         {
               "id": "C001095",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001095.json",
               "first_name": "Tom",
               "middle_name": null,
               "last_name": "Cotton",
               "suffix": null,
               "date_of_birth": "1977-05-13",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenTomCotton",
               "facebook_account": "SenatorTomCotton",
               "youtube_account": "RepTomCotton",
               "govtrack_id": "412508",
               "cspan_id": "63928",
               "votesmart_id": "135651",
               "icpsr_id": "21301",
               "crp_id": "N00033363",
               "google_entity_id": "/m/02g3ds",
               "fec_candidate_id": "H2AR04083",
               "url": "https://www.cotton.senate.gov",
               "rss_url": "https://www.cotton.senate.gov/rss/",
               "contact_form": "http://www.cotton.senate.gov/?p=contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.579,
               "ideal_point": null,
               "seniority": "5",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 1,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:ar",
               "office": "326 Russell Senate Office Building",
               "phone": "202-224-2353",
               "fax": null,
               "state": "AR",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S374"
               ,"missed_votes_pct": 0.25,
               "votes_with_party_pct": 97.20,
               "votes_against_party_pct": 2.80
             },
                         {
               "id": "C001096",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001096.json",
               "first_name": "Kevin",
               "middle_name": null,
               "last_name": "Cramer",
               "suffix": null,
               "date_of_birth": "1961-01-21",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenKevinCramer",
               "facebook_account": "CongressmanKevinCramer",
               "youtube_account": "kevincramer",
               "govtrack_id": "412555",
               "cspan_id": "7600",
               "votesmart_id": "444",
               "icpsr_id": "21350",
               "crp_id": "N00004614",
               "google_entity_id": "/m/02rhrnw",
               "fec_candidate_id": "H0ND01026",
               "url": "https://www.cramer.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.cramer.senate.gov/contact_kevin",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.388,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 4,
               "total_present": 0,
               "last_updated": "2019-12-13 08:45:51 -0500",
               "ocd_id": "ocd-division/country:us/state:nd",
               "office": "400 Russell Senate Office Building",
               "phone": "202-224-2043",
               "fax": null,
               "state": "ND",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S398"
               ,"missed_votes_pct": 1.01,
               "votes_with_party_pct": 99.49,
               "votes_against_party_pct": 0.51
             },
                         {
               "id": "C000880",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C000880.json",
               "first_name": "Michael",
               "middle_name": "D.",
               "last_name": "Crapo",
               "suffix": null,
               "date_of_birth": "1951-05-20",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "MikeCrapo",
               "facebook_account": "mikecrapo",
               "youtube_account": "senatorcrapo",
               "govtrack_id": "300030",
               "cspan_id": "26440",
               "votesmart_id": "26830",
               "icpsr_id": "29345",
               "crp_id": "N00006267",
               "google_entity_id": "/m/021pgp",
               "fec_candidate_id": "S8ID00027",
               "url": "https://www.crapo.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.crapo.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.511,
               "ideal_point": null,
               "seniority": "21",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 4,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:id",
               "office": "239 Dirksen Senate Office Building",
               "phone": "202-224-6142",
               "fax": "202-228-1375",
               "state": "ID",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S266"
               ,"missed_votes_pct": 1.01,
               "votes_with_party_pct": 97.95,
               "votes_against_party_pct": 2.05
             },
                         {
               "id": "C001098",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/C001098.json",
               "first_name": "Ted",
               "middle_name": null,
               "last_name": "Cruz",
               "suffix": null,
               "date_of_birth": "1970-12-22",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenTedCruz",
               "facebook_account": "SenatorTedCruz",
               "youtube_account": "sentedcruz",
               "govtrack_id": "412573",
               "cspan_id": "1019953",
               "votesmart_id": "135705",
               "icpsr_id": "41304",
               "crp_id": "N00033085",
               "google_entity_id": "/m/07j6ty",
               "fec_candidate_id": "S2TX00312",
               "url": "https://www.cruz.senate.gov",
               "rss_url": "https://www.cruz.senate.gov/rss/",
               "contact_form": "https://www.cruz.senate.gov/?p=form&id=16",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.824,
               "ideal_point": null,
               "seniority": "7",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 14,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:tx",
               "office": "127a Russell Senate Office Building",
               "phone": "202-224-5922",
               "fax": null,
               "state": "TX",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S355"
               ,"missed_votes_pct": 3.54,
               "votes_with_party_pct": 92.89,
               "votes_against_party_pct": 7.11
             },
                         {
               "id": "D000618",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/D000618.json",
               "first_name": "Steve",
               "middle_name": null,
               "last_name": "Daines",
               "suffix": null,
               "date_of_birth": "1962-08-20",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SteveDaines",
               "facebook_account": "SteveDainesMT",
               "youtube_account": "SteveDainesMT",
               "govtrack_id": "412549",
               "cspan_id": "1034037",
               "votesmart_id": "135720",
               "icpsr_id": "21338",
               "crp_id": "N00033054",
               "google_entity_id": "/m/03qlc5t",
               "fec_candidate_id": "H2MT01060",
               "url": "https://www.daines.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.daines.senate.gov/connect/email-steve",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.552,
               "ideal_point": null,
               "seniority": "5",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 6,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:mt",
               "office": "320 Hart Senate Office Building",
               "phone": "202-224-2651",
               "fax": "202-228-1236",
               "state": "MT",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S375"
               ,"missed_votes_pct": 1.52,
               "votes_with_party_pct": 93.56,
               "votes_against_party_pct": 6.44
             },
                         {
               "id": "D000622",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/D000622.json",
               "first_name": "Tammy",
               "middle_name": null,
               "last_name": "Duckworth",
               "suffix": null,
               "date_of_birth": "1968-03-12",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenDuckworth",
               "facebook_account": "SenDuckworth",
               "youtube_account": "repduckworth",
               "govtrack_id": "412533",
               "cspan_id": "94484",
               "votesmart_id": "57442",
               "icpsr_id": "21325",
               "crp_id": "N00027860",
               "google_entity_id": "/m/09vqjr",
               "fec_candidate_id": "H6IL06141",
               "url": "https://www.duckworth.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.duckworth.senate.gov/content/contact-senator",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.334,
               "ideal_point": null,
               "seniority": "3",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 18,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:il",
               "office": "524 Hart Senate Office Building",
               "phone": "202-224-2854",
               "fax": null,
               "state": "IL",
               "senate_class": "3",
               "state_rank": "junior",
               "lis_id": "S386"
               ,"missed_votes_pct": 4.55,
               "votes_with_party_pct": 94.28,
               "votes_against_party_pct": 5.72
             },
                         {
               "id": "D000563",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/D000563.json",
               "first_name": "Richard",
               "middle_name": "J.",
               "last_name": "Durbin",
               "suffix": null,
               "date_of_birth": "1944-11-21",
               "gender": "M",
               "party": "D",
               "leadership_role": "Senate Minority Whip",
               "twitter_account": "SenatorDurbin",
               "facebook_account": "SenatorDurbin",
               "youtube_account": "SenatorDurbin",
               "govtrack_id": "300038",
               "cspan_id": "6741",
               "votesmart_id": "26847",
               "icpsr_id": "15021",
               "crp_id": "N00004981",
               "google_entity_id": "/m/01xcd1",
               "fec_candidate_id": "S6IL00151",
               "url": "https://www.durbin.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.durbin.senate.gov/contact/",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.355,
               "ideal_point": null,
               "seniority": "23",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 6,
               "total_present": 1,
               "last_updated": "2019-12-13 15:46:25 -0500",
               "ocd_id": "ocd-division/country:us/state:il",
               "office": "711 Hart Senate Office Building",
               "phone": "202-224-2152",
               "fax": "202-228-0400",
               "state": "IL",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S253"
               ,"missed_votes_pct": 1.52,
               "votes_with_party_pct": 94.70,
               "votes_against_party_pct": 5.31
             },
                         {
               "id": "E000285",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/E000285.json",
               "first_name": "Michael",
               "middle_name": "B.",
               "last_name": "Enzi",
               "suffix": null,
               "date_of_birth": "1944-02-01",
               "gender": "M",
               "party": "R",
               "leadership_role": "",
               "twitter_account": "SenatorEnzi",
               "facebook_account": "mikeenzi",
               "youtube_account": "senatorenzi",
               "govtrack_id": "300041",
               "cspan_id": "45824",
               "votesmart_id": "558",
               "icpsr_id": "49706",
               "crp_id": "N00006249",
               "google_entity_id": "/m/021ph1",
               "fec_candidate_id": "S6WY00126",
               "url": "https://www.enzi.senate.gov",
               "rss_url": "https://www.enzi.senate.gov/public/?a=rss.feed",
               "contact_form": "http://www.enzi.senate.gov/public/index.cfm/contact?p=e-mail-senator-enzi",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.542,
               "ideal_point": null,
               "seniority": "23",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 2,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:wy",
               "office": "379a Russell Senate Office Building",
               "phone": "202-224-3424",
               "fax": "202-228-0359",
               "state": "WY",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S254"
               ,"missed_votes_pct": 0.51,
               "votes_with_party_pct": 96.94,
               "votes_against_party_pct": 3.06
             },
                         {
               "id": "E000295",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/E000295.json",
               "first_name": "Joni",
               "middle_name": null,
               "last_name": "Ernst",
               "suffix": null,
               "date_of_birth": "1970-07-01",
               "gender": "F",
               "party": "R",
               "leadership_role": "Senate Republican Conference Vice Chair",
               "twitter_account": "SenJoniErnst",
               "facebook_account": "senjoniernst",
               "youtube_account": null,
               "govtrack_id": "412667",
               "cspan_id": "75342",
               "votesmart_id": "128583",
               "icpsr_id": "41502",
               "crp_id": "N00035483",
               "google_entity_id": "/m/0gg4wkg",
               "fec_candidate_id": "S4IA00129",
               "url": "https://www.ernst.senate.gov/public",
               "rss_url": "https://www.ernst.senate.gov/public/?a=rss.feed",
               "contact_form": "https://www.ernst.senate.gov/public/index.cfm/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.527,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 6,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:ia",
               "office": "730 Hart Senate Office Building",
               "phone": "202-224-3254",
               "fax": null,
               "state": "IA",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S376"
               ,"missed_votes_pct": 1.52,
               "votes_with_party_pct": 97.16,
               "votes_against_party_pct": 2.84
             },
                         {
               "id": "F000062",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/F000062.json",
               "first_name": "Dianne",
               "middle_name": null,
               "last_name": "Feinstein",
               "suffix": null,
               "date_of_birth": "1933-06-22",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenFeinstein",
               "facebook_account": "senatorfeinstein",
               "youtube_account": "SenatorFeinstein",
               "govtrack_id": "300043",
               "cspan_id": "13061",
               "votesmart_id": "53273",
               "icpsr_id": "49300",
               "crp_id": "N00007364",
               "google_entity_id": "/m/01gqws",
               "fec_candidate_id": "S0CA00199",
               "url": "https://www.feinstein.senate.gov",
               "rss_url": "https://www.feinstein.senate.gov/public/?a=rss.feed",
               "contact_form": "https://www.feinstein.senate.gov/public/index.cfm/e-mail-me",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.269,
               "ideal_point": null,
               "seniority": "27",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:ca",
               "office": "331 Hart Senate Office Building",
               "phone": "202-224-3841",
               "fax": null,
               "state": "CA",
               "senate_class": "1",
               "state_rank": "senior",
               "lis_id": "S221"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 94.26,
               "votes_against_party_pct": 5.74
             },
                         {
               "id": "F000463",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/F000463.json",
               "first_name": "Deb",
               "middle_name": null,
               "last_name": "Fischer",
               "suffix": null,
               "date_of_birth": "1951-03-01",
               "gender": "F",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenatorFischer",
               "facebook_account": "senatordebfischer",
               "youtube_account": "senatordebfischer",
               "govtrack_id": "412556",
               "cspan_id": "1034067",
               "votesmart_id": "41963",
               "icpsr_id": "41302",
               "crp_id": "N00033443",
               "google_entity_id": "/m/0c4cp0",
               "fec_candidate_id": "S2NE00094",
               "url": "https://www.fischer.senate.gov",
               "rss_url": null,
               "contact_form": "http://www.fischer.senate.gov/public/index.cfm/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.473,
               "ideal_point": null,
               "seniority": "7",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 6,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:ne",
               "office": "454 Russell Senate Office Building",
               "phone": "202-224-6551",
               "fax": null,
               "state": "NE",
               "senate_class": "1",
               "state_rank": "senior",
               "lis_id": "S357"
               ,"missed_votes_pct": 1.52,
               "votes_with_party_pct": 98.20,
               "votes_against_party_pct": 1.80
             },
                         {
               "id": "G000562",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/G000562.json",
               "first_name": "Cory",
               "middle_name": null,
               "last_name": "Gardner",
               "suffix": null,
               "date_of_birth": "1974-08-22",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenCoryGardner",
               "facebook_account": "SenCoryGardner",
               "youtube_account": null,
               "govtrack_id": "412406",
               "cspan_id": "623308",
               "votesmart_id": "30004",
               "icpsr_id": "21112",
               "crp_id": "N00030780",
               "google_entity_id": "/m/0czd33q",
               "fec_candidate_id": "H0CO04122",
               "url": "https://www.gardner.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.gardner.senate.gov/contact-cory/email-cory",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.446,
               "ideal_point": null,
               "seniority": "5",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 4,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:co",
               "office": "354 Russell Senate Office Building",
               "phone": "202-224-5941",
               "fax": "202-225-5870",
               "state": "CO",
               "senate_class": "2",
               "state_rank": "junior",
               "lis_id": "S377"
               ,"missed_votes_pct": 1.01,
               "votes_with_party_pct": 97.18,
               "votes_against_party_pct": 2.82
             },
                         {
               "id": "G000555",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/G000555.json",
               "first_name": "Kirsten",
               "middle_name": "E.",
               "last_name": "Gillibrand",
               "suffix": null,
               "date_of_birth": "1966-12-09",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "GillibrandNY",
               "facebook_account": "SenKirstenGillibrand",
               "youtube_account": "KirstenEGillibrand",
               "govtrack_id": "412223",
               "cspan_id": "1022862",
               "votesmart_id": "65147",
               "icpsr_id": "20735",
               "crp_id": "N00027658",
               "google_entity_id": "/m/0gnfc4",
               "fec_candidate_id": "H6NY20167",
               "url": "https://www.gillibrand.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.gillibrand.senate.gov/contact/email-me",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.459,
               "ideal_point": null,
               "seniority": "11",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 110,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:ny",
               "office": "478 Russell Senate Office Building",
               "phone": "202-224-4451",
               "fax": null,
               "state": "NY",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S331"
               ,"missed_votes_pct": 27.78,
               "votes_with_party_pct": 73.84,
               "votes_against_party_pct": 26.16
             },
                         {
               "id": "G000359",
               "title": "Senator, 2nd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/G000359.json",
               "first_name": "Lindsey",
               "middle_name": null,
               "last_name": "Graham",
               "suffix": null,
               "date_of_birth": "1955-07-09",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "GrahamBlog",
               "facebook_account": "USSenatorLindseyGraham",
               "youtube_account": "USSenLindseyGraham",
               "govtrack_id": "300047",
               "cspan_id": "36782",
               "votesmart_id": "21992",
               "icpsr_id": "29566",
               "crp_id": "N00009975",
               "google_entity_id": "/m/01_pdg",
               "fec_candidate_id": "S0SC00149",
               "url": "https://www.lgraham.senate.gov/public",
               "rss_url": "https://www.lgraham.senate.gov/public/?a=rss.feed",
               "contact_form": "https://www.lgraham.senate.gov/public/index.cfm/e-mail-senator-graham",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.406,
               "ideal_point": null,
               "seniority": "17",
               "next_election": "2020",
               "total_votes": 396,
               "missed_votes": 11,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:sc",
               "office": "290 Russell Senate Office Building",
               "phone": "202-224-5972",
               "fax": "202-224-3808",
               "state": "SC",
               "senate_class": "2",
               "state_rank": "senior",
               "lis_id": "S293"
               ,"missed_votes_pct": 2.78,
               "votes_with_party_pct": 97.65,
               "votes_against_party_pct": 2.35
             },
                         {
               "id": "G000386",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/G000386.json",
               "first_name": "Charles",
               "middle_name": "E.",
               "last_name": "Grassley",
               "suffix": null,
               "date_of_birth": "1933-09-17",
               "gender": "M",
               "party": "R",
               "leadership_role": "President Pro Tempore of the Senate",
               "twitter_account": "ChuckGrassley",
               "facebook_account": "grassley",
               "youtube_account": "senchuckgrassley",
               "govtrack_id": "300048",
               "cspan_id": "1167",
               "votesmart_id": "53293",
               "icpsr_id": "14226",
               "crp_id": "N00001758",
               "google_entity_id": "/m/020ymy",
               "fec_candidate_id": "S0IA00028",
               "url": "https://www.grassley.senate.gov",
               "rss_url": "https://www.grassley.senate.gov/?q=rss.xml",
               "contact_form": "http://www.grassley.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": 0.346,
               "ideal_point": null,
               "seniority": "39",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 0,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:ia",
               "office": "135 Hart Senate Office Building",
               "phone": "202-224-3744",
               "fax": "202-224-6020",
               "state": "IA",
               "senate_class": "3",
               "state_rank": "senior",
               "lis_id": "S153"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 97.72,
               "votes_against_party_pct": 2.28
             },
                         {
               "id": "H001075",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/H001075.json",
               "first_name": "Kamala",
               "middle_name": null,
               "last_name": "Harris",
               "suffix": null,
               "date_of_birth": "1964-10-20",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "SenKamalaHarris",
               "facebook_account": "SenatorKamalaHarris",
               "youtube_account": null,
               "govtrack_id": "412678",
               "cspan_id": "1018696",
               "votesmart_id": "120012",
               "icpsr_id": "41701",
               "crp_id": "N00036915",
               "google_entity_id": "/m/08sry2",
               "fec_candidate_id": "S6CA00584",
               "url": "https://www.harris.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.harris.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.714,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 233,
               "total_present": 1,
               "last_updated": "2019-12-13 16:25:22 -0500",
               "ocd_id": "ocd-division/country:us/state:ca",
               "office": "112 Hart Senate Office Building",
               "phone": "202-224-3553",
               "fax": null,
               "state": "CA",
               "senate_class": "3",
               "state_rank": "junior",
               "lis_id": "S387"
               ,"missed_votes_pct": 58.84,
               "votes_with_party_pct": 72.96,
               "votes_against_party_pct": 27.04
             },
                         {
               "id": "H001076",
               "title": "Senator, 3rd Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/H001076.json",
               "first_name": "Margaret",
               "middle_name": null,
               "last_name": "Hassan",
               "suffix": null,
               "date_of_birth": "1958-02-27",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "Senatorhassan",
               "facebook_account": "SenatorHassan",
               "youtube_account": null,
               "govtrack_id": "412680",
               "cspan_id": "67481",
               "votesmart_id": "42552",
               "icpsr_id": "41702",
               "crp_id": "N00038397",
               "google_entity_id": "/m/03c3zch",
               "fec_candidate_id": "S6NH00091",
               "url": "https://www.hassan.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.hassan.senate.gov/content/contact-senator",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.241,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2022",
               "total_votes": 396,
               "missed_votes": 1,
               "total_present": 1,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:nh",
               "office": "324 Hart Senate Office Building",
               "phone": "202-224-3324",
               "fax": null,
               "state": "NH",
               "senate_class": "3",
               "state_rank": "junior",
               "lis_id": "S388"
               ,"missed_votes_pct": 0.25,
               "votes_with_party_pct": 91.88,
               "votes_against_party_pct": 8.12
             },
                         {
               "id": "H001089",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/H001089.json",
               "first_name": "Joshua",
               "middle_name": null,
               "last_name": "Hawley",
               "suffix": null,
               "date_of_birth": "1979-12-31",
               "gender": "M",
               "party": "R",
               "leadership_role": null,
               "twitter_account": "SenHawleyPress",
               "facebook_account": null,
               "youtube_account": null,
               "govtrack_id": "412840",
               "cspan_id": null,
               "votesmart_id": "169716",
               "icpsr_id": null,
               "crp_id": "N00041620",
               "google_entity_id": "/g/11bwy_95zy",
               "fec_candidate_id": "S8MO00160",
               "url": "https://www.hawley.senate.gov",
               "rss_url": null,
               "contact_form": "https://www.hawley.senate.gov/contact-senator-hawley",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": null,
               "ideal_point": null,
               "seniority": "1",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 0,
               "total_present": 0,
               "last_updated": "2019-12-13 06:48:44 -0500",
               "ocd_id": "ocd-division/country:us/state:mo",
               "office": "212 Russell Senate Office Building",
               "phone": "202-224-6154",
               "fax": null,
               "state": "MO",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S399"
               ,"missed_votes_pct": 0.00,
               "votes_with_party_pct": 95.69,
               "votes_against_party_pct": 4.31
             },
                         {
               "id": "H001046",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/H001046.json",
               "first_name": "Martin",
               "middle_name": null,
               "last_name": "Heinrich",
               "suffix": null,
               "date_of_birth": "1971-10-17",
               "gender": "M",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "MartinHeinrich",
               "facebook_account": "MartinHeinrich",
               "youtube_account": "SenMartinHeinrich",
               "govtrack_id": "412281",
               "cspan_id": "1030686",
               "votesmart_id": "74517",
               "icpsr_id": "20930",
               "crp_id": "N00029835",
               "google_entity_id": "/m/02qkv0r",
               "fec_candidate_id": "H8NM01224",
               "url": "https://www.heinrich.senate.gov",
               "rss_url": "https://www.heinrich.senate.gov/rss/feeds/?type=all",
               "contact_form": "http://www.heinrich.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.316,
               "ideal_point": null,
               "seniority": "7",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 11,
               "total_present": 1,
               "last_updated": "2019-12-12 15:01:31 -0500",
               "ocd_id": "ocd-division/country:us/state:nm",
               "office": "303 Hart Senate Office Building",
               "phone": "202-224-5521",
               "fax": null,
               "state": "NM",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S359"
               ,"missed_votes_pct": 2.78,
               "votes_with_party_pct": 93.55,
               "votes_against_party_pct": 6.45
             },
                         {
               "id": "H001042",
               "title": "Senator, 1st Class",
               "short_title": "Sen.",
               "api_uri":"https://api.propublica.org/congress/v1/members/H001042.json",
               "first_name": "Mazie",
               "middle_name": "K.",
               "last_name": "Hirono",
               "suffix": null,
               "date_of_birth": "1947-11-03",
               "gender": "F",
               "party": "D",
               "leadership_role": null,
               "twitter_account": "MazieHirono",
               "facebook_account": "senatorhirono",
               "youtube_account": "CongresswomanHirono",
               "govtrack_id": "412200",
               "cspan_id": "91216",
               "votesmart_id": "1677",
               "icpsr_id": "20713",
               "crp_id": "N00028139",
               "google_entity_id": "/m/0357cd",
               "fec_candidate_id": "H6HI02251",
               "url": "https://www.hirono.senate.gov",
               "rss_url": "https://www.hirono.senate.gov/rss/feeds/",
               "contact_form": "https://www.hirono.senate.gov/contact",
               "in_office": true,
               "cook_pvi": null,
               "dw_nominate": -0.507,
               "ideal_point": null,
               "seniority": "7",
               "next_election": "2024",
               "total_votes": 396,
               "missed_votes": 18,
               "total_present": 1,
               "last_updated": "2019-12-13 16:25:22 -0500",
               "ocd_id": "ocd-division/country:us/state:hi",
               "office": "713 Hart Senate Office Building",
               "phone": "202-224-6361",
               "fax": null,
               "state": "HI",
               "senate_class": "1",
               "state_rank": "junior",
               "lis_id": "S361"
               ,"missed_votes_pct": 4.55,
               "votes_with_party_pct": 81.15,
               "votes_against_party_pct": 18.85
             }]
  }]
        }